[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowfunding = "3NJSWfTkaAULwdG7AniHTHwKmAB1nVEsuaRbzMCB9DDt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
